name: vint-action
description: 'Lint your vimscript with vint'
inputs:
  path:
    description: 'Paths to files or directories to be included by the linter.'
    required: true
  args:
    description: 'Args passed to vint. See https://github.com/Vimjas/vint#command-line-config.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.args }}

branding:
  icon: terminal
  color: green
